# Generated by Django 3.2.9 on 2021-11-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('pk_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_section_width', models.PositiveSmallIntegerField()),
                ('f_aspect_ratio', models.PositiveSmallIntegerField()),
                ('f_rim_diameter', models.PositiveSmallIntegerField()),
                ('r_section_width', models.PositiveSmallIntegerField()),
                ('r_aspect_ratio', models.PositiveSmallIntegerField()),
                ('r_rim_diameter', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'tires',
            },
        ),
    ]
